version: '3'

services:
  # Node.js service
  web:
    image: node:alpine
    container_name: node-app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  # MySQL service
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
